name: lesehan
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.0.0
  image_picker: ^0.8.4+3
  shared_preferences: ^2.0.6
  intl: ^0.17.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.8.0
  google_maps_flutter: ^2.2.5
  geocoding: ^2.0.5
  permission_handler: ^10.2.0
  flutter_animate: ^4.2.0
  flutter_slidable: ^2.0.0


  cupertino_icons: ^1.0.8
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  assets:
  - assets/


  uses-material-design: true
